version: "2"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.0
    container_name: es 
    ports:
      - "9200:9200"
    networks:
      - esnet
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.0
    container_name: logstash
    networks:
      - esnet
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
      - ./logs/:/logs/

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - esnet
    environment:
      SERVER_NAME: kibana-local
      ELASTICSEARCH_URL: http://es:9200

networks:
  esnet:
    driver: bridge

volumes:
  esdata1:
